# Generated by Django 5.2.1 on 2025-10-25 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnchantmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=50, verbose_name='장비 종류')),
                ('recommended_enchants', models.JSONField(default=list, verbose_name='추천 인챈트 (ID)')),
                ('general_enchants', models.JSONField(default=list, verbose_name='일반 인챈트 (ID)')),
                ('not_recommended_enchants', models.JSONField(default=list, verbose_name='비추천 인챈트 (ID)')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '인챈트 추천 게시물',
                'verbose_name_plural': '인챈트 추천 게시물',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='enchant_recommender.enchantmentrecommendation', verbose_name='게시물')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enchant_likes', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 누른 사용자')),
            ],
            options={
                'verbose_name': '게시물 좋아요',
                'verbose_name_plural': '게시물 좋아요',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
