# Generated by Django 5.2.1 on 2025-10-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enchant_recommender', '0002_enchantmentrecommendation_likes_count_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enchantmentrecommendation',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='게시물 제목'),
        ),
    ]
